feat: adiciona modal com para escolher disciplinas optativas
UnBArqDsw2022-1/2022.1_G4_FluxoAgil-web pull request #32
Opened 2022-08-18 13:26 UTC by yudi-azvd

Ainda tem que ser decidido

- [ ] como vai ser rastreado o estado "global" da aplicação. Se tá na página de upload do histórico, na página de resultados parciais/visão geral ou na página de resultado final (recomendação).
- [ ] como vai ser feita a query para listar a optativas no modal e como retornar as optativas escolhidas pro restante da aplicação.

O primeiro item é um decisão mais geral, tem que conversar mais com o time. O segundo acho que é mais específico.

Closes #2

2022-08-19 00:29 UTC, yudi-azvd commented
![image](https://user-images.githubusercontent.com/37981839/185517031-8b802d65-cbe3-42b4-91e4-8708a50c4697.png)

Ficamos na dúvida em como implementar essa parte do "cursando". Prevejo um prop drilling, a não ser que essa informação seja salva num context API e dentro do modal a gente use `useContext`/`useCoursesFromPdf`.

2022-08-19 00:30 UTC, yudi-azvd commented
Falta fazer:

- [ ] definir a chamada pra API 
- [ ] mudar detalhes de estilização (cores, espaçamento etc)

2022-08-23 00:35 UTC, yudi-azvd commented
Mini tutorial para testar:

No frontend você deve habilitar a renderização da modal no arquivo `src/containers/App.tsx:20`:

```diff
-{academicHistory ? (
+{!academicHistory ? (
  <RecommendationSettings />
) : (
  <AcademicHistoryUpload />
)}
```

É uma mudança temporária e **não** deve ser commitada.

No backend adicione o arquivo `courses.json` na raíz do projeto com o seguinte conteúdo:

```json
[
  { "id": "1", "label": "Cálculo numérico", "workloadInHours": 60 },
  { "id": "2", "label": "Desenho mecânico", "workloadInHours": 90 },
  { "id": "3", "label": "Algoritmo e programação de computadores", "workloadInHours": 90 },
  { "id": "4", "label": "Introdução à engenharia", "workloadInHours": 30 },
  { "id": "5", "label": "Humanidades e cidadania", "workloadInHours": 60 }
]
```

E `fluxoagil/__init__.py` assim

```py
from flask import Flask
from flask_cors import CORS
from flask_restful import Resource, Api, reqparse

import json

class HelloFluxoAgil(Resource):
    def get(self):
        return {'Welcome': 'to Fluxo Agil API'}

class Courses(Resource):
    def get(self):
        f = open('courses.json')
        courses = json.load(f)
        print(courses)
        f.close()
        return courses

def create_app():
    app = Flask(__name__)
    api = Api(app)
    cors = CORS(app, resources={r"*": {"origins": "*"}})
    app.config['SECRET KEY'] = ''
    api.add_resource(HelloFluxoAgil, '/')
    api.add_resource(Courses, '/courses')
    return app
```

Essa também é apenas uma mudança temporária para fazer o frontend consultar o backend que vai devolver os cursos. **Nâo deve ser commitada**.

2022-08-23 22:59 UTC, irwinschmitt requested changes
Essas tags estão quebrando muito o layout e aparentemente os checkboxes não estão funcionando.

![image](https://user-images.githubusercontent.com/44441530/186280448-df32e93a-af96-4e49-87d0-174a7651203c.png)

2022-08-23 22:59 UTC, irwinschmitt commented on src/components/SelectOptionalCoursesModal.tsx
> +              variant="outlined"
O contraste do verde claro com o branco não ficou muito bom, sugiro utilizar nossa cor secundária.

```suggestion
              color="secondary"
              variant="outlined"
```

2022-08-23 22:59 UTC, irwinschmitt commented on src/types/index.ts
> +  label: string
O que acha de utilizar `title`, ao invés de `label`?

2022-08-23 22:59 UTC, irwinschmitt commented on src/components/SelectOptionalCoursesModal.tsx
> +            onClick={() => setSelectedOptionalCourses([])}
Podíamos utilizar a regra do ESLint de não utilizar arrow functions diretamente nas props e ter um handler

2022-08-23 22:59 UTC, irwinschmitt commented on src/components/SelectOptionalCoursesModal.tsx
> +          <Typography color={colors['green-4']} marginBottom="16px">
Acho melhor utilizar o nosso `p` padrão, mudando a cor somente no id do currículo.

E utilizar os breakpoints em número, porque conseguimos mudar o valor desses números no tema. Se utilizar "64px" direto, perdemos esse controle no tema. No padrão, cada unidade corresponde a 8px (p=1 é equivalente a p="8px").

```suggestion
          <Typography mb={2}>
```

2022-08-23 22:59 UTC, irwinschmitt commented on src/components/SelectOptionalCoursesModal.tsx
> +  setSelectedOptionalCourses: (courses: OptionalCourse[]) => void
Pra salvar na store, o redux recomenda utilizar os hooks, como no exemplo no `AcademicHistoryUpload`:

```js
const dispatch = useDispatch()
dispatch(setOptionalCourses(optionalCourses))
```

2022-08-23 23:00 UTC, irwinschmitt commented on src/components/SelectOptionalCoursesModal.tsx
> +  setSelectedOptionalCourses: (courses: OptionalCourse[]) => void
https://react-redux.js.org/api/hooks#usedispatch

2022-08-23 23:07 UTC, irwinschmitt requested changes

2022-08-23 23:07 UTC, irwinschmitt commented on src/components/SelectOptionalCoursesModal.tsx
> +      >
Aqui acho melhor utilizar as props do componente.

https://smartdevpreneur.com/when-to-use-the-mui-sx-prop-styled-api-or-theme-override/

2022-08-23 23:07 UTC, irwinschmitt commented on src/components/SelectOptionalCoursesModal.tsx
> +        <Box marginBottom="8px" display="flex" color={colors['green-4']}>
```suggestion
        <Box mb={1} display="flex">
```

2022-08-23 23:07 UTC, irwinschmitt commented on src/components/SelectOptionalCoursesModal.tsx
> +          <Typography>{curriculaeId}</Typography>
Acredito que o plural de _curriculum_ mais utilizado seja _curricula_.

2022-08-24 03:22 UTC, yudi-azvd commented on src/components/SelectOptionalCoursesModal.tsx
> +              variant="outlined"
Fiz essa mudança e não notei nenhuma diferença

2022-08-24 03:23 UTC, yudi-azvd commented on src/components/SelectOptionalCoursesModal.tsx
> +              variant="outlined"
Na real, a caixa do Autoselect fica um verde mais escuro, é isso?

2022-08-24 03:45 UTC, yudi-azvd commented on src/components/SelectOptionalCoursesModal.tsx
> +            onClick={() => setSelectedOptionalCourses([])}
Por que não deixar assim? Não vejo essa função sendo utilizada em outro lugar

2022-08-24 03:50 UTC, yudi-azvd commented on src/components/SelectOptionalCoursesModal.tsx
> +        <Box marginBottom="8px" display="flex" color={colors['green-4']}>
Troquei, mas acho que a cor de antes estava melhor

2022-08-24 12:46 UTC, yudi-azvd commented on src/components/SelectOptionalCoursesModal.tsx
> +  setSelectedOptionalCourses: (courses: OptionalCourse[]) => void
Fiz as seguintes modificações:

`store/optionalCourses.ts`

```ts
/* eslint-disable no-param-reassign */
import { createSlice, PayloadAction } from '@reduxjs/toolkit'
import { OptionalCourse, OptionalCoursesStore, RootState } from '@/types'

const initialState: OptionalCoursesStore = {
  optionalCourses: [],
}

export const optionalCoursesSlice = createSlice({
  name: 'optionalCourses',
  initialState,
  reducers: {
    setOptionalCourses: (state, action: PayloadAction<OptionalCourse[]>) => {
      state.optionalCourses = action.payload
    },
  },
})

export const { setOptionalCourses } = optionalCoursesSlice.actions

export default optionalCoursesSlice.reducer

export const selectOptionalCourses = (state: RootState) =>
  state.optionalCourses.optionalCourses
```

`store/index.ts`

```diff
import { recommendationApi } from '@/api'
import { configureStore } from '@reduxjs/toolkit'
import recommendation from './recommendation'
+import optionalCourses from './optionalCourses'

export default configureStore({
  reducer: {
    recommendation,
    [recommendationApi.reducerPath]: recommendationApi.reducer,
    optionalCourses,
  },
  middleware: getDefaultMiddleware =>
    getDefaultMiddleware().concat(recommendationApi.middleware),
})
```

2022-08-24 13:11 UTC, yudi-azvd commented on src/components/SelectOptionalCoursesModal.tsx
> +  setSelectedOptionalCourses: (courses: OptionalCourse[]) => void
Depois desse comentário eu mudei a store `optionalCourses` pra `selectedOptionalCourses` pra não ficar confuso lá no Autocomplete da modal

2022-08-25 01:57 UTC, irwinschmitt approved these changes

2022-08-25 02:57 UTC, merged